sudo: required
services:
  - docker

before_install:
  - docker build -t ashish91/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ashish91/react-test npm test -- --coverage

after_success:
  - docker build -t ashish91/multi-client ./client
  - docker build -t ashish91/mult-nginx ./nginx
  - docker build -t ashish91/multi-server ./server
  - docker build -t ashish91/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push ashish91/multi-client
  - docker push ashish91/multi-nginx
  - docker push ashish91/multi-server
  - docker push ashish91/multi-worker
